swagger: "2.0"
info:
  version: 1.0.0
  title: Swagger Place Ranking Generator
  license:
    name: MIT
host: wsil.swagger.io
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /rankPlacesToLive:
    get:
      summary: Get ordered list of places to lived based on proximity to important places
      operationId: rankPlacesToLive
      parameters:
        - name: placesToLive
          in: query
          description: The Google maps place IDs for places to live that will be ranked based on their proximity to the important places
          required: true
          type: array
          items:
            type: string
        - name: importantPlaces
          in: query
          description: The Google maps place IDs the potential places to live will be evaluated against
          required: true
          type: array
          items:
            type: string
      responses:
        "200":
          description: List of potential places to live, ranked by suitability
          schema:
            $ref: '#/definitions/PlaceRankSummaries'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'

definitions:
  PlaceRankSummary:
    type: "object"
    required:
      - name
      - totalTravelTimePerMonth
    properties:
      name:
        type: string
        description: Google Maps place name
      success:
        type: boolean
        description: Whether a sucessful distance matrix element was returned for this place
      totalTravelTimePerMonth:
        type: integer
        format: int64
        description: Total time over a month travelling if lived at the place with associated id
  PlaceRankSummaries:
    type: array
    items:
      $ref: '#/definitions/PlaceRankSummary'
  Error:
    type: "object"
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string