swagger: "2.0"
info:
  version: 1.0.0
  title: Swagger Place Ranking Generator
  license:
    name: MIT
host: wsil.swagger.io
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /rankPlacesToLive:
    get:
      summary: Get ordered list of places to lived based on proximity to important places
      operationId: rankPlacesToLive
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          type: integer
          format: int32
      responses:
        "200":
          description: List of potential places to live, ranked by suitability
          schema:
            $ref: '#/definitions/PlaceRankSummaries'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'

definitions:
  PlaceRankSummary:
    type: "object"
    required:
      - id
      - name
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      tag:
        type: string
  PlaceRankSummaries:
    type: array
    items:
      $ref: '#/definitions/PlaceRankSummary'
  Error:
    type: "object"
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string