swagger: "2.0"
info:
  version: 1.0.0
  title: Swagger Place Ranking Generator
  license:
    name: MIT
host: wsil.swagger.io
basePath: /v1
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /rankPlacesToLive:
    post:
      summary: Get ordered list of places to lived based on proximity to important places
      consumes:
        - application/json
      parameters:
        - in: body
          name: requestBody
          schema:
            type: object
            properties:
              placesToLive:
                description: The Google maps place IDs for places to live that will be ranked based on their proximity to the important places
                type: array
                items:
                  type: string
              importantPlaces:
                description: The Google maps place IDs the potential places to live will be evaluated against
                type: array
                items:
                  $ref: '#/definitions/ImportantPlace'
      responses:
        "200":
          description: List of potential places to live, ranked by suitability
          schema:
            $ref: '#/definitions/PlaceRankSummaries'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'

definitions:
  ImportantPlace:
    type: "object"
    required:
      - id
      - visitsPerMonth
    properties:
      id:
        type: string
        description: Google Maps place id
      visitsPerMonth:
        type: number
        format: float
        description: Number of times this place is visited in one month
  PlaceRankSummary:
    type: "object"
    required:
      - name
      - totalTravelTimePerMonth
    properties:
      name:
        type: string
        description: Google Maps place name
      success:
        type: boolean
        description: Whether a sucessful distance matrix element was returned for this place
      totalTravelTimePerMonth:
        type: number
        format: float
        description: Total time over a month travelling if lived at the place with associated id
  PlaceRankSummaries:
    type: array
    items:
      $ref: '#/definitions/PlaceRankSummary'
  Error:
    type: "object"
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string